; PlatformIO Project Configuration File for T-Dongle-S3
; 
; Use the Project Environment Switcher in the status bar to pick which example to build.

[platformio]
default_envs = day_date
src_dir = examples

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Memory & Flash Settings
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

; Build Flags for Hardware and Display
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-D USER_SETUP_LOADED=1

; Global Library Dependencies
lib_deps = 
	mathertel/OneButton@^2.6.1
	fastled/FastLED@^3.9.4

; --- EXAMPLES ---


[env:day_date]
build_src_filter = +<day_date/src/>
build_flags = 
	${env.build_flags}
	-Iexamples/day_date/include
	-Ibangla_font_support_example/extras/FontsHeader
lib_deps = 
	${env.lib_deps}
	adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
	adafruit/Adafruit GFX Library @ ^1.11.9
	symlink://bangla_font_support_example

[env:bangla_day_date]
build_src_filter = +<bangla_day_date/src/>
build_flags = 
	${env.build_flags}
	-Iexamples/bangla_day_date/include
	-Ibangla_font_support_example/extras/FontsHeader
lib_deps = 
	${env.lib_deps}
	adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
	adafruit/Adafruit GFX Library @ ^1.11.9
	symlink://bangla_font_support_example
